# Generated by Django 5.2.4 on 2025-07-13 14:17

from django.db import migrations

CATEGORIES = [
    "Неоновые вывески",
    "Объемные буквы",
    "Световые кубы",
    "Таблички",
    "Печать",
    "Нестандартные изделия",
]

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    for i, category_name in enumerate(CATEGORIES):
        Category.objects.create(name=category_name, order=i)

def delete_initial_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Category.objects.filter(name__in=CATEGORIES).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_work'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_code=delete_initial_categories),
    ]
