# Generated by Django 5.2.4 on 2025-07-13 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/', verbose_name='Изображение')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Изображение работы',
                'verbose_name_plural': 'Изображения работ',
            },
        ),
    ]
