# Generated by Django 5.2.4 on 2025-07-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_question_surveysubmission_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное описание'),
        ),
    ]
