# Generated by Django 5.2.4 on 2025-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_testimonial_alter_surveysubmission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Мета-описание (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок (SEO)'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL (slug)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_content',
            field=models.TextField(verbose_name='Полное содержимое'),
        ),
    ]
