server {
    listen 80;
    server_name api.bogorodovneon.ru;
    
    location / {
        return 301 https://$host$request_uri;
    }
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name api.bogorodovneon.ru;
    
    ssl_certificate /etc/letsencrypt/live/bogorodovneon.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bogorodovneon.ru/privkey.pem;
    
    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /static/ {
        alias /static/;
    }
    
    location /media/ {
        alias /media/;
    }
}